
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywudgkmrbbwpcbvlakrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3dWRna21yYmJ3cGNidmxha3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzE3NjksImV4cCI6MjA1OTg0Nzc2OX0.ng6SmC8e2fG67UrUgjZ3eWKH9fnegdmwJdJGC8k8XjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
